# Generated by Django 6.1.1 on 2026-09-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboracion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(blank=True, default=dict, verbose_name="cambios"),
        ),
    ]
