# Generated by Django 6.1.1 on 2026-09-14 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('avance', models.PositiveIntegerField()),
                ('meta', models.PositiveIntegerField()),
                ('cumplimiento_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('semaforo', models.CharField(choices=[('verde', 'Verde'), ('ambar', 'Ámbar'), ('rojo', 'Rojo')], max_length=10)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='core.cargo')),
                ('delegacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='core.delegacion')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='funcionarios.funcionario')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='core.periodo')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ponderacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.JSONField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponderaciones', to='core.cargo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponderaciones', to='core.periodo')),
            ],
            options={
                'verbose_name': 'Ponderación',
                'verbose_name_plural': 'Ponderaciones',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.PositiveIntegerField()),
                ('ponderador', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='core.cargo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='core.periodo')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='core.tipoactividad')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['cargo', 'periodo'],
                'constraints': [models.UniqueConstraint(fields=('cargo', 'periodo', 'tipo_actividad'), name='unique_meta_cargo_periodo_tipo')],
            },
        ),
    ]
