# Generated by Django 6.1.1 on 2026-09-27 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                ("progress", models.PositiveIntegerField(verbose_name="avance")),
                ("target", models.PositiveIntegerField(verbose_name="meta")),
                (
                    "compliance_pct",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="cumplimiento (%)"
                    ),
                ),
                (
                    "traffic_light",
                    models.CharField(
                        choices=[
                            ("green", "Verde"),
                            ("amber", "Ámbar"),
                            ("red", "Rojo"),
                        ],
                        max_length=10,
                        verbose_name="semáforo",
                    ),
                ),
                (
                    "delegation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="core.delegation",
                        verbose_name="delegación",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="funcionarios.employee",
                        verbose_name="funcionario",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="core.period",
                        verbose_name="período",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="core.position",
                        verbose_name="cargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador",
                "verbose_name_plural": "Indicadores",
                "db_table": "indicator",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Weighting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.JSONField(verbose_name="detalle")),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de generación"
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weightings",
                        to="core.period",
                        verbose_name="período",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weightings",
                        to="core.position",
                        verbose_name="cargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ponderación",
                "verbose_name_plural": "Ponderaciones",
                "db_table": "weighting",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.PositiveIntegerField(verbose_name="meta")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="ponderador"
                    ),
                ),
                (
                    "activity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="core.activitytype",
                        verbose_name="tipo de actividad",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="core.period",
                        verbose_name="período",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="core.position",
                        verbose_name="cargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta",
                "verbose_name_plural": "Metas",
                "db_table": "goal",
                "ordering": ["position", "period"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("position", "period", "activity_type"),
                        name="unique_goal_position_period_type",
                    )
                ],
            },
        ),
    ]
