# Generated by Django 6.1.1 on 2026-09-14 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('accion', models.CharField(blank=True, max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('indicador_agenda', models.BooleanField(default=False)),
                ('codigo_evidencia', models.CharField(max_length=40, unique=True)),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='core.delegacion')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='funcionarios.funcionario')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='core.periodo')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='core.tipoactividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AtencionSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_gestion', models.PositiveSmallIntegerField()),
                ('descripcion', models.TextField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones_sociales', to='actividades.actividad')),
            ],
            options={
                'verbose_name': 'Atención social',
                'verbose_name_plural': 'Atenciones sociales',
                'ordering': ['actividad', 'numero_gestion'],
                'constraints': [models.UniqueConstraint(fields=('actividad', 'numero_gestion'), name='unique_gestion_por_actividad')],
            },
        ),
    ]
