# Generated by Django 6.1.1 on 2026-09-27 02:14

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=30, unique=True, verbose_name="número"),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                ("description", models.TextField(verbose_name="descripción")),
                (
                    "action",
                    models.CharField(blank=True, max_length=200, verbose_name="acción"),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="contacto"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono"
                    ),
                ),
                (
                    "is_agenda_item",
                    models.BooleanField(
                        default=False, verbose_name="indicador de agenda"
                    ),
                ),
                (
                    "evidence_code",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="código de evidencia"
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobada"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado de validación",
                    ),
                ),
                (
                    "activity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="core.activitytype",
                        verbose_name="tipo de actividad",
                    ),
                ),
                (
                    "delegation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="core.delegation",
                        verbose_name="delegación",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="funcionarios.employee",
                        verbose_name="funcionario",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="core.period",
                        verbose_name="período",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "db_table": "activity",
                "ordering": ["-date"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SocialCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                (
                    "step_number",
                    models.PositiveSmallIntegerField(verbose_name="número de gestión"),
                ),
                ("description", models.TextField(verbose_name="descripción")),
                (
                    "activity",
                    models.ForeignKey(
                        limit_choices_to={"deleted_at__isnull": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_cases",
                        to="actividades.activity",
                        verbose_name="actividad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atención social",
                "verbose_name_plural": "Atenciones sociales",
                "db_table": "social_case",
                "ordering": ["activity", "step_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activity", "step_number"),
                        name="unique_step_per_activity",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
