# Generated by Django 6.1.1 on 2026-09-27 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actividades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialcase",
            name="step_number",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="número de gestión",
            ),
        ),
    ]
