# Generated by Django 6.1.1 on 2026-09-27 02:04

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actividades", "0002_alter_actividad_periodo"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="actividad",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="atencionsocial",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="actividad",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="eliminado el",
            ),
        ),
        migrations.AddField(
            model_name="atencionsocial",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="eliminado el",
            ),
        ),
        migrations.AlterField(
            model_name="atencionsocial",
            name="actividad",
            field=models.ForeignKey(
                limit_choices_to={"deleted_at__isnull": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atenciones_sociales",
                to="actividades.actividad",
            ),
        ),
    ]
