# Generated by Django 6.1.1 on 2026-09-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="código"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("service", "Atención"),
                            ("paperwork", "Tramitación"),
                            ("field_work", "Operativo"),
                            ("social", "Atención social"),
                        ],
                        max_length=20,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="subtipo"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
            ],
            options={
                "verbose_name": "Tipo de actividad",
                "verbose_name_plural": "Tipos de actividad",
                "db_table": "activity_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Delegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="nombre"
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="dirección")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
            ],
            options={
                "verbose_name": "Delegación",
                "verbose_name_plural": "Delegaciones",
                "db_table": "delegation",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=60, unique=True, verbose_name="clave"),
                ),
                ("value", models.CharField(max_length=120, verbose_name="valor")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
            ],
            options={
                "verbose_name": "Parámetro",
                "verbose_name_plural": "Parámetros",
                "db_table": "parameter",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="nombre"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="fecha de inicio")),
                ("end_date", models.DateField(verbose_name="fecha de término")),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="cerrado"),
                ),
                (
                    "min_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=80.0,
                        max_digits=5,
                        verbose_name="umbral mínimo",
                    ),
                ),
                (
                    "max_cap",
                    models.DecimalField(
                        decimal_places=2,
                        default=150.0,
                        max_digits=5,
                        verbose_name="tope máximo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Período",
                "verbose_name_plural": "Períodos",
                "db_table": "period",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "area",
                    models.CharField(blank=True, max_length=120, verbose_name="área"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "db_table": "position",
                "ordering": ["name"],
            },
        ),
    ]
