# Generated by Django 6.1.1 on 2026-09-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="max_cap",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                max_digits=5,
                verbose_name="tope máximo",
            ),
        ),
    ]
