# Generated by Django 6.1.1 on 2026-09-30 23:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_period_max_cap"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="creado el",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activitytype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modificado el"),
        ),
        migrations.AddField(
            model_name="delegation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="creado el",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delegation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modificado el"),
        ),
        migrations.AddField(
            model_name="parameter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="creado el",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parameter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modificado el"),
        ),
        migrations.AddField(
            model_name="period",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="creado el",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="period",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modificado el"),
        ),
        migrations.AddField(
            model_name="position",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="creado el",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="position",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modificado el"),
        ),
    ]
