# Generated by Django 6.1.1 on 2026-09-27 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "delegation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="core.delegation",
                        verbose_name="delegación",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="core.position",
                        verbose_name="cargo",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionario",
                "verbose_name_plural": "Funcionarios",
                "db_table": "employee",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(max_length=128, verbose_name="hash del código"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expira")),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="intentos"
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="usado")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de recuperación",
                "verbose_name_plural": "Códigos de recuperación",
                "db_table": "password_reset_code",
                "ordering": ["-created_at"],
            },
        ),
    ]
