# Generated by Django 6.1.1 on 2026-09-27 02:14

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("due_date", models.DateField(verbose_name="fecha de vencimiento")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Ingresado"),
                            ("pending", "Pendiente"),
                            ("in_progress", "En proceso"),
                            ("done", "Realizado"),
                        ],
                        default="registered",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observaciones")),
                (
                    "delegation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commitments",
                        to="core.delegation",
                        verbose_name="delegación",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commitments",
                        to="funcionarios.employee",
                        verbose_name="responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compromiso",
                "verbose_name_plural": "Compromisos",
                "db_table": "commitment",
                "ordering": ["due_date"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CommitmentFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="fecha")),
                ("description", models.TextField(verbose_name="descripción")),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("registered", "Ingresado"),
                            ("pending", "Pendiente"),
                            ("in_progress", "En proceso"),
                            ("done", "Realizado"),
                        ],
                        max_length=20,
                        verbose_name="estado nuevo",
                    ),
                ),
                (
                    "commitment",
                    models.ForeignKey(
                        limit_choices_to={"deleted_at__isnull": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="agenda.commitment",
                        verbose_name="compromiso",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups",
                        to="funcionarios.employee",
                        verbose_name="responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de compromiso",
                "verbose_name_plural": "Seguimientos de compromiso",
                "db_table": "commitment_follow_up",
                "ordering": ["-date"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
