# Generated by Django 6.1.1 on 2026-09-14 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('realizado', 'Realizado')], default='ingresado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='core.delegacion')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromisos', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Compromiso',
                'verbose_name_plural': 'Compromisos',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoCompromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado_nuevo', models.CharField(choices=[('ingresado', 'Ingresado'), ('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('realizado', 'Realizado')], max_length=20)),
                ('compromiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='agenda.compromiso')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Seguimiento de compromiso',
                'verbose_name_plural': 'Seguimientos de compromiso',
                'ordering': ['-fecha'],
            },
        ),
    ]
