# Generated by Django 6.1.1 on 2026-09-27 02:14

import django.db.models.deletion
import django.db.models.manager
import evidencias.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actividades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="eliminado el",
                    ),
                ),
                (
                    "unique_code",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        unique=True,
                        verbose_name="código único",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=evidencias.models.ruta_evidencia,
                        verbose_name="archivo",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de registro"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobada"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="resultado"
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        limit_choices_to={"deleted_at__isnull": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="actividades.activity",
                        verbose_name="actividad",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_evidence",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="revisada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidencia",
                "verbose_name_plural": "Evidencias",
                "db_table": "evidence",
                "ordering": ["-registered_at"],
                "permissions": [("can_approve_evidence", "Puede aprobar evidencias")],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Validation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="fecha")),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "Aprobada"), ("rejected", "Rechazada")],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="comentario")),
                (
                    "evidence",
                    models.ForeignKey(
                        limit_choices_to={"deleted_at__isnull": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="evidencias.evidence",
                        verbose_name="evidencia",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="verificador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validación",
                "verbose_name_plural": "Validaciones",
                "db_table": "validation",
                "ordering": ["-date"],
            },
        ),
    ]
