# Generated by Django 6.1.1 on 2026-09-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidencia',
            options={'ordering': ['-fecha_registro'], 'permissions': [('can_approve_evidencia', 'Puede aprobar evidencias')], 'verbose_name': 'Evidencia', 'verbose_name_plural': 'Evidencias'},
        ),
    ]
