# Generated by Django 6.1.1 on 2026-09-27 23:08

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidencias", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="validation",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="validation",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="eliminado el",
            ),
        ),
    ]
