# Generated by Django 6.1.1 on 2026-09-30 23:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidencias", "0002_alter_validation_managers_validation_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="creado el",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evidence",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modificado el"),
        ),
        migrations.AddField(
            model_name="validation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="creado el",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="validation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modificado el"),
        ),
    ]
