# Generated by Django 6.1.1 on 2026-09-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0002_alter_evidencia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='codigo_unico',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
