# Generated by Django 6.1.1 on 2026-09-26 21:26

import evidencias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidencias", "0003_alter_evidencia_codigo_unico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidencia",
            name="archivo",
            field=models.FileField(
                blank=True, null=True, upload_to=evidencias.models.ruta_evidencia
            ),
        ),
    ]
