# Generated by Django 6.1.1 on 2026-09-27 02:04

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actividades", "0003_alter_actividad_managers_and_more"),
        ("evidencias", "0004_alter_evidencia_archivo"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="evidencia",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="evidencia",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="eliminado el",
            ),
        ),
        migrations.AlterField(
            model_name="evidencia",
            name="actividad",
            field=models.ForeignKey(
                limit_choices_to={"deleted_at__isnull": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidencias",
                to="actividades.actividad",
            ),
        ),
        migrations.AlterField(
            model_name="validacion",
            name="evidencia",
            field=models.ForeignKey(
                limit_choices_to={"deleted_at__isnull": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validaciones",
                to="evidencias.evidencia",
            ),
        ),
    ]
