"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Sin valor por defecto en el código: debe venir del .env (ver .env.example).
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'Falta SECRET_KEY en el .env. Genere una con: '
        'python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
    )

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto apagado: en desarrollo se activa con DEBUG=True en el .env.
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

# Orígenes confiables para formularios POST (CSRF) cuando se accede por dominio/IP pública,
# por ejemplo: CSRF_TRUSTED_ORIGINS=http://ec2-3-80-1-2.compute-1.amazonaws.com,https://sgr.midominio.cl
CSRF_TRUSTED_ORIGINS = [
    origen.strip() for origen in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origen.strip()
]

# Detrás de nginx con HTTPS: nginx informa el esquema original en X-Forwarded-Proto.
if os.getenv('BEHIND_HTTPS_PROXY', 'False') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'funcionarios',
    'actividades',
    'evidencias',
    'agenda',
    'medicion',
    'monitoreo',
    'reportes',
    'colaboracion',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# MySQL / MariaDB (en AWS: Amazon RDS). SQLite ya no se usa en este proyecto.
# Django 6.1 exige MySQL 8.4+ o MariaDB 10.11+ y el driver mysqlclient 2.2.1+.
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', 'sgr'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        # Reutiliza conexiones entre peticiones (segundos); 0 = cerrar al final de cada petición.
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
        'OPTIONS': {
            # utf8mb4: tildes, ñ y emojis completos (el "utf8" de MySQL solo cubre 3 bytes).
            'charset': 'utf8mb4',
            # Modo estricto: MySQL rechaza datos inválidos en vez de truncarlos en silencio.
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        'TEST': {
            'NAME': os.getenv('DB_TEST_NAME', 'test_' + os.getenv('DB_NAME', 'sgr')),
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4_unicode_ci',
        },
    }
}

# Conexión cifrada a RDS: descargar el bundle de certificados de AWS y apuntar DB_SSL_CA a él.
if os.getenv('DB_SSL_CA'):
    DATABASES['default']['OPTIONS']['ssl'] = {'ca': os.getenv('DB_SSL_CA')}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        # Mayúscula, minúscula, número y carácter especial (core/validators.py).
        'NAME': 'core.validators.ComplexPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

# Traducciones propias (locale/es) para textos de Django 6.1 que aún no vienen en español.
LOCALE_PATHS = [BASE_DIR / 'locale']

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# En producción: python manage.py collectstatic reúne aquí los archivos y nginx los sirve.
STATIC_ROOT = BASE_DIR / os.getenv('STATIC_ROOT_DIR', 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / os.getenv('MEDIA_ROOT_DIR', 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Django 6.1 reemplaza EMAIL_BACKEND/EMAIL_HOST/... por MAILERS (definir ambos es un error),
# así que las mismas variables de entorno de la guía se leen dentro de MAILERS.
# En desarrollo el backend de consola imprime el correo en la terminal.

EMAIL_BACKEND_ENV = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
MAILERS = {
    'default': {
        'BACKEND': EMAIL_BACKEND_ENV,
    },
}
if EMAIL_BACKEND_ENV.endswith('smtp.EmailBackend'):
    MAILERS['default']['OPTIONS'] = {
        'host': os.getenv('EMAIL_HOST', ''),
        'port': int(os.getenv('EMAIL_PORT', '2525')),
        'username': os.getenv('EMAIL_HOST_USER', ''),
        'password': os.getenv('EMAIL_HOST_PASSWORD', ''),
        'use_tls': os.getenv('EMAIL_USE_TLS', 'True') == 'True',
    }
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'SGR La Serena <no-responder@demo.sgr.local>')


# Autenticación (rutas de django.contrib.auth.urls montadas en config/urls.py)
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


# Mensajes: el nivel ERROR usa la clase "danger" de Bootstrap (alert-error no existe).
from django.contrib.messages import constants as message_constants  # noqa: E402

MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.ERROR: 'danger',
}


# Sesiones y cookies: COOKIE_SECURE=True solo en producción con HTTPS.
COOKIE_SECURE = os.getenv('COOKIE_SECURE', 'False').lower() == 'true'
SESSION_COOKIE_AGE = 60 * 60 * 2  # 2 horas
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_SECURE = COOKIE_SECURE
CSRF_COOKIE_SECURE = COOKIE_SECURE
SESSION_COOKIE_SAMESITE = 'Lax'


# Recuperación de contraseña mediante código temporal
RECUPERACION_CODIGO_VIGENCIA_SEGUNDOS = int(os.getenv('RECUPERACION_CODIGO_VIGENCIA_SEGUNDOS', '120'))
RECUPERACION_CODIGO_MAX_INTENTOS = 5
RECUPERACION_MAX_SOLICITUDES_HORA = 5  # códigos que un mismo usuario puede pedir por hora


# Archivos de evidencia
EVIDENCIA_TAMANO_MAXIMO_MB = 2
