# Generated by Django 6.1.1 on 2026-09-14 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableroPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('personal', 'Personal'), ('delegacion', 'Delegación'), ('global', 'Global')], max_length=20)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tableros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tablero/Panel',
                'verbose_name_plural': 'Tableros/Paneles',
                'ordering': ['nombre'],
            },
        ),
    ]
